# https://source.redhat.com/departments/strategy_and_operations/it/identityaccessmanagement/it_iam_ipa/specification_idm_infrastructure#jive_content_id_Prod
redhat.ldap.dn=cn=users,cn=accounts,dc=ipa,dc=redhat,dc=com
redhat.ldap.connection=admin1.idm-001.prod.iad2.dc.redhat.com
redhat.ldap.port=389
redhat.ldap.warmup-user=gahealy
redhat.ldap.kerberos.realm=IPA.REDHAT.COM
redhat.ldap.kerberos.kdc=${redhat.ldap.connection}

quarkus.log.category."org.apache.directory.api.ldap.codec".level=WARN
quarkus.log.category."org.apache.directory.api.ldap.extras".level=WARN

# LoginContext ServiceLoader plus GSSAPI Kerberos (native image)
quarkus.native.auto-service-loader-registration=true
quarkus.native.additional-build-args=-H:AdditionalSecurityProviders=sun.security.jgss.SunProvider,-H:IncludeResourceBundles=sun.security.util.resources.security

quarkus.native.resources.includes=**/phonenumbers/data/**
